Ajouté infos sur Formulaires
EduWireApps/ecoledirecte-api-docs pull request #21
Opened 2024-01-08 20:03 UTC by MrBeam89

Ajout des informations sur les formulaires (data en body et contenu de la réponse)

2024-01-25 19:13 UTC, MaitreRouge commented
Désolé, je n'ai pas été actif dernièrement sur la doc ED, je vérifie juste l'exactitude des informations et je reviens vers toi

2024-01-25 19:22 UTC, MaitreRouge requested changes
J'ai pas de compte ED qui possède de formulaires à l'heure actuelle, j'ai juste regardé l'intégrité de ce que tu voulais push. Je te félicite et te remercie de ta participation mais est-ce possible de raccourcir un peu l'exemple que tu donnes. On cherche pas à avoir un exemple de formulaire mais savoir comment la réponse est formatée. Donc peut-être tu pourrais un peu "raccourcir" la réponse histoire qu'on sache ce que renvoie cet endpoint sans pour autant surcharger la doc

2024-01-25 19:22 UTC, MaitreRouge commented on README.md
> +    "idEntity": // id élève
Normal que le JSON soit invalide ?

2024-01-25 21:56 UTC, MrBeam89 commented on README.md
> +    "idEntity": // id élève
Probablement dû au commentaire, je l'ai remplacé par 1234 dans le commit

2024-01-25 21:59 UTC, MrBeam89 commented
J'ai effectué les changements (raccourci l'exemple et rajouté quelques précisions), 

> Je te félicite et te remercie de ta participation

C'est vous que je dois remercier !

Bonne soirée

2024-02-10 12:19 UTC, azgaresncf commented on README.md
> +            "id": 15347, // ?
Probablement que tu es le 15347ème participant ? Même si c'est plutôt bizarre.

2024-02-11 13:52 UTC, amolinarius commented
@MrBeam89 Je me suis dit que j'allais faire une PR parce que j'avais un formulaire et j'ai vu la tienne mdr

2024-02-11 19:37 UTC, azgaresncf commented
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/50982832/389d23d2-43ec-439b-8b1e-c68aed5d57dc)

2024-02-17 15:07 UTC, MaitreRouge approved these changes

2024-02-17 15:10 UTC, MaitreRouge commented
@azgaresncf tu as quelque chose à reprocher au contenu de la PR avant que je la merge ?

2024-02-17 17:14 UTC, azgaresncf commented
> @azgaresncf tu as quelque chose à reprocher au contenu de la PR avant que je la merge ?

Nan rien !

2024-02-17 17:14 UTC, azgaresncf commented
C'était juste pour ajouter les détails

2024-02-18 12:49 UTC, merged